#SPDX-License-Identifier: MIT-0
---
# tasks file for haproxy-1
#
- name: Install haproxy package to hosts
  dnf:
    name: haproxy
    state: present

- name: Start and Enable haproxy
  service:
    name: haproxy
    state: started
    enabled: true

- name: Create a haproxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart haproxy
