---
- name: Enable internet service
  hosts: serverb.ingtondemo.com
  become: true

  tasks:
    - name: Install packages
      dnf:
        name: 
          - httpd
          - mariadb-server
          - firewalld
          - php
          - php-mysqlnd
        state: latest

    - name: Enable and start Firewall Service
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Enable http serivce under firewall
      firewalld:
        service: http
        immediate: true
        permanent: true
        state: enabled

    - name: Enable and start httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: Enable and start mariadb
      service: 
        name: mariadb
        state: started
        enabled: true

    - name: Create a index.html from template
      template:
        src: files/index.html.j2
        dest: /var/www/html/index.html
        mode: 0644


- name: Check the internet serices are running
  hosts: test
  become: false
  tasks:
    - name: Verify the status of internet service
      uri:
        url: http://serverb.ingtondemo.com:82
        status_code: 200

