$ANSIBLE_VAULT;1.1;AES256
36643062306430633131373762316231316237376239643637333266623565323536616635373139
3833626336333231663764373038343038383935353662630a333939343034303564653262623661
37663935636435363366646365343035336165353430623063376631353434663062393432373739
3661653434316539610a313162363030346630323165613162356232366533333265646162633464
31323738313635343362343338306533343233646533363164313963613430303663653836373361
3530353232666230653536396162383362663233323932616364
